---
root_passwd: "redhat"
ca_dir: "/root/ca_dir"

ipa_server_ip: ""
ipa_server_hostname: "ipa-server.sc.test.com"
ipa_client_hostname: "ipa-client.sc.test.com"
ipa_domain: "sc.test.com"
ipa_realm: "SC.TEST.COM"
ipa_server_admin_passwd: "SECret.123"

local_user:
    name: "local-user"
    passwd: "654321"
    pin: "123456"
    card_dir: "/root/local-user"
    local: true
ipa_user:
  name: "ipa-user"
  passwd: "ipa-user-passwd"
  pin: "SECret.123"
  card_dir: "/root/krb_user"
  local: false
